# 
# File Generated by GEOS buildExec 
# Copyright (c) 2023 DefinitelyNotAGirl@github 
#
include make/modules.make
include make/klib.module.make
include make/INIT.module.make
include make/FUNCDIS.module.make
include make/MALLOC.module.make
include make/gfs0.fs.module.make
include make/fat32.fs.module.make
include make/SATAN.module.make
include make/modinclude.make
