# 
# File Generated by GEOS buildExec 
# Copyright (c) 2023 DefinitelyNotAGirl@github 
#
MALLOC_SOURCE_asm_asm=$(wildcard modules/MALLOC/src/*.asm)
MALLOC_OBJECTS_asm_asm=$(patsubst modules/MALLOC/src/%.asm,build/MALLOC/%.o,$(MALLOC_SOURCE_asm_asm))
MALLOC_DEPFILES_asm_asm=$(patsubst modules/MALLOC/src/%.asm,build/MALLOC/%.d,$(MALLOC_SOURCE_asm_asm))
MALLOC_SOURCE_asm_s=$(wildcard modules/MALLOC/src/*.s)
MALLOC_OBJECTS_asm_s=$(patsubst modules/MALLOC/src/%.s,build/MALLOC/%.o,$(MALLOC_SOURCE_asm_s))
MALLOC_DEPFILES_asm_s=$(patsubst modules/MALLOC/src/%.s,build/MALLOC/%.d,$(MALLOC_SOURCE_asm_s))
MALLOC_SOURCE_cpp_cpp=$(wildcard modules/MALLOC/src/*.cpp)
MALLOC_OBJECTS_cpp_cpp=$(patsubst modules/MALLOC/src/%.cpp,build/MALLOC/%.o,$(MALLOC_SOURCE_cpp_cpp))
MALLOC_DEPFILES_cpp_cpp=$(patsubst modules/MALLOC/src/%.cpp,build/MALLOC/%.d,$(MALLOC_SOURCE_cpp_cpp))
MALLOC_SOURCE_cpp_cxx=$(wildcard modules/MALLOC/src/*.cxx)
MALLOC_OBJECTS_cpp_cxx=$(patsubst modules/MALLOC/src/%.cxx,build/MALLOC/%.o,$(MALLOC_SOURCE_cpp_cxx))
MALLOC_DEPFILES_cpp_cxx=$(patsubst modules/MALLOC/src/%.cxx,build/MALLOC/%.d,$(MALLOC_SOURCE_cpp_cxx))
MALLOC_SOURCE_c_c=$(wildcard modules/MALLOC/src/*.c)
MALLOC_OBJECTS_c_c=$(patsubst modules/MALLOC/src/%.c,build/MALLOC/%.o,$(MALLOC_SOURCE_c_c))
MALLOC_DEPFILES_c_c=$(patsubst modules/MALLOC/src/%.c,build/MALLOC/%.d,$(MALLOC_SOURCE_c_c))
build/MALLOC/%.o: modules/MALLOC/src/%.asm
	@../TrinityOS/tools/as-new -W -M -MD -c -o $@ $<
	$(info  	[35m[COMPILE][0m	$<)
build/MALLOC/%.o: modules/MALLOC/src/%.s
	@../TrinityOS/tools/as-new -W -M -MD -c -o $@ $<
	$(info  	[35m[COMPILE][0m	$<)
build/MALLOC/%.o: modules/MALLOC/src/%.cpp
	@g++ -O0 -fno-rtti -fno-exceptions -nostdlib -ffreestanding -fno-stack-protector -fno-builtin -nostartfiles -Wunreachable-code -std=c++20 -w -Wno-literal-suffix -Wno-pointer-arith -MP -MD -Imodules/klib/inc/ -Iinc/ -Ishared/ -Imodules/MALLOC/inc -march=x86-64 -c -o $@ $<
	$(info 	[35m[COMPILE][0m	$<)
build/MALLOC/%.o: modules/MALLOC/src/%.cxx
	@g++ -O0 -fno-rtti -fno-exceptions -nostdlib -ffreestanding -fno-stack-protector -fno-builtin -nostartfiles -Wunreachable-code -std=c++20 -w -Wno-literal-suffix -Wno-pointer-arith -MP -MD -Imodules/klib/inc/ -Iinc/ -Ishared/ -Imodules/MALLOC/inc -march=x86-64 -c -o $@ $<
	$(info 	[35m[COMPILE][0m	$<)
build/MALLOC/%.o: modules/MALLOC/src/%.c
	@gcc -Wunreachable-code -Imodules/klib/inc/ -Iinc/ -Ishared/ -Imodules/MALLOC/inc -march=x86-64 -c -o $@ $<
	$(info  	[35m[COMPILE][0m	$<)
m-MALLOC-clean:
	@-rm -r build/MALLOC/*.o > /dev/null
	$(info  	[33m[CLEAN][0m	build/MALLOC/*.o)
	@-rm -r build/MALLOC/*.d > /dev/null
	$(info  	[33m[CLEAN][0m	build/MALLOC/*.d)
m-MALLOC: out/kernel/MALLOC.elf64
out/kernel/MALLOC.elf64:  $(MALLOC_OBJECTS_asm_asm) $(MALLOC_OBJECTS_asm_s) $(MALLOC_OBJECTS_cpp_cpp) $(MALLOC_OBJECTS_cpp_cxx) $(MALLOC_OBJECTS_c_c)
	@ld -nostdlib -w -T LDS/MALLOC.ld  $(MALLOC_OBJECTS_asm_asm) $(MALLOC_OBJECTS_asm_s) $(MALLOC_OBJECTS_cpp_cpp) $(MALLOC_OBJECTS_cpp_cxx) $(MALLOC_OBJECTS_c_c)  $(klib_OBJECTS_asm_asm) $(klib_OBJECTS_asm_s) $(klib_OBJECTS_cpp_cpp) $(klib_OBJECTS_cpp_cxx) $(klib_OBJECTS_c_c) -o out/kernel/MALLOC.elf64
	$(info  	[34m[LINK][0m	$@)
	@objcopy out/kernel/MALLOC.elf64  --remove-section text_klib --remove-section rodata_klib --remove-section data_klib --remove-section bss_klib &> /dev/null
-include $(MALLOC_DEPFILES_asm_asm)
-include $(MALLOC_DEPFILES_asm_s)
-include $(MALLOC_DEPFILES_cpp_cpp)
-include $(MALLOC_DEPFILES_cpp_cxx)
-include $(MALLOC_DEPFILES_c_c)
