# 
# File Generated by GEOS buildExec 
# Copyright (c) 2023 DefinitelyNotAGirl@github 
#
inc/INIT: modules/INIT/inc/INIT.h
	 cp $< $@
	$(info  	COPY	$<)
inc/FUNCDIS: modules/FUNCDIS/inc/FUNCDIS.h
	 cp $< $@
	$(info  	COPY	$<)
inc/MALLOC: modules/MALLOC/inc/MALLOC.h
	 cp $< $@
	$(info  	COPY	$<)
inc/gfs0.fs: modules/gfs0.fs/inc/gfs0.fs.h
	 cp $< $@
	$(info  	COPY	$<)
inc/fat32.fs: modules/fat32.fs/inc/fat32.fs.h
	 cp $< $@
	$(info  	COPY	$<)
inc/SATAN: modules/SATAN/inc/SATAN.h
	 cp $< $@
	$(info  	COPY	$<)
modinc-all: inc/INIT inc/FUNCDIS inc/MALLOC inc/gfs0.fs inc/fat32.fs inc/SATAN 
